In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])
print(arr1)
print()
print(arr1.ndim)

[1 2 3 4 5]

1


In [3]:
arr2=np.array([[1,2],[3,4]])
print(arr2)
print()
print(arr2.ndim)

[[1 2]
 [3 4]]

2


In [4]:
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)
print()
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

3


In [5]:
arr4=np.array([1,2,3,4,5,6,6,7,8,10],ndmin=4)
print(arr4)

[[[[ 1  2  3  4  5  6  6  7  8 10]]]]


# Numpy Functions

In [6]:
arr5=np.zeros(5)
print(arr5)

[0. 0. 0. 0. 0.]


In [7]:
arr5=np.zeros((2,3))
print(arr5)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
arr6=np.ones(5)
print(arr6)

[1. 1. 1. 1. 1.]


arr7=np.ones((3,3))
print(arr7)

In [9]:
arr8=np.eye(3,3)
print(arr8)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Range Functions 

In [10]:
arr9=np.arange(1,10)
print(arr9)

[1 2 3 4 5 6 7 8 9]


# Linspace

In [11]:
arr10=np.linspace(1,5,num=5)
print(arr10)

[1. 2. 3. 4. 5.]


# Random_Functions

In [12]:
arr11=np.random.rand(5) # rand has a value range from 0 to 1 only
print(arr11)

[0.71410045 0.12753721 0.95970661 0.34339514 0.21955658]


In [13]:
arr12=np.random.rand(5,5) # rand has a value range from 0 to 1 only
print(arr12)

[[3.00060090e-01 1.14011807e-01 4.90954280e-01 9.67727478e-01
  4.00226954e-04]
 [2.67402684e-01 9.39993706e-01 5.04716073e-01 1.85259545e-01
  3.27464115e-01]
 [8.04266029e-01 3.03461507e-01 6.17409876e-02 7.80345056e-01
  4.17845000e-01]
 [2.27083654e-02 2.86264900e-01 7.27888021e-02 6.69837930e-01
  3.42209686e-01]
 [3.51032483e-01 5.55471395e-01 9.13858520e-01 3.53400562e-01
  2.83984982e-02]]


In [14]:
arr13=np.random.randn(8) # randn function has a value range from 0 to 1 and contain positive and negative numbers
print(arr13)

[-1.25777319 -0.65346732 -0.59149419  0.10051655  1.04324628  0.83696553
 -1.0297759  -0.41638695]


In [15]:
arr13=np.random.randn(2,8) # randn function has a value range from 0 to 1 and contain positive and negative numbers
print(arr13)

[[ 0.38483021 -0.70646371  0.39664148  0.62513827  0.99645859  1.19518843
   0.24322414  0.19346274]
 [-0.61368583 -0.69702955  0.59676478 -0.73362992  0.72849463 -0.30590068
   0.04321295 -0.31274011]]


In [16]:
arr14=np.random.ranf(10) # ranf function has a value range from close to 0 but not include one
print(arr14)

[0.04818727 0.32422298 0.52811347 0.39220677 0.15168886 0.04421174
 0.9296509  0.10568337 0.30480043 0.01427201]


In [17]:
arr15=np.random.randint(1,10,9) # randint function has integer value 
print(arr15)

[6 9 4 4 7 8 9 6 9]


# DataType Functions

In [18]:
arr16=np.array([1.,2.,3.,4.])
print(arr16.dtype)

float64


In [19]:
arr16=np.array([1,2,3,4])
print(arr16.dtype)

int64


In [20]:
arr17=np.array([1,2,3,4,5])
print("The Array Before converting into another data type is:-")
print(arr17)
print()
print("The Array After converting into another data type is:-")
arr17=np.array([1,2,3,4,5],dtype='f')
print(arr17)

The Array Before converting into another data type is:-
[1 2 3 4 5]

The Array After converting into another data type is:-
[1. 2. 3. 4. 5.]


In [21]:
arr18=np.array([[1,2],[3,4],[5,6]])
arr19=arr18.astype(float) # astype func converts one datatype into another datatype (most fequently and commnly used in industry function)
print(arr19)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


# Shaping And Reshaping Array Functions

In [22]:
arr20=np.array([[1,2],[3,4],[5,6]])
print(arr20)
print()
print("The Array is of:-",arr20.ndim,"Dimensions Array")
print()
print("The Shape Of And Array is:-",arr20.shape)

[[1 2]
 [3 4]
 [5 6]]

The Array is of:- 2 Dimensions Array

The Shape Of And Array is:- (3, 2)


In [23]:
arr21=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr21)
print()
print("The Array is of:-",arr21.ndim,"Dimensions Array")
print()
print("The Shape Of And Array is:-",arr21.shape)

[ 1  2  3  4  5  6  7  8  9 10]

The Array is of:- 1 Dimensions Array

The Shape Of And Array is:- (10,)


In [24]:
arr21=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr21)
print()
print("The Array is of:-",arr21.ndim,"Dimensions Array")
print()
print("The Shape Of And Array is:-",arr21.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

The Array is of:- 3 Dimensions Array

The Shape Of And Array is:- (1, 3, 3)


In [25]:
arr22=np.array([1,2,3,4,5,6])
print("The Before reshaping is:-",arr22)
print()
arr22=np.array([1,2,3,4,5,6]).reshape(3,2)
print("The Array After reshaping is:-")
print(arr22)

The Before reshaping is:- [1 2 3 4 5 6]

The Array After reshaping is:-
[[1 2]
 [3 4]
 [5 6]]


In [26]:
arr23=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("The Before reshaping is:-",arr23)
print()
arr23=np.array([[[1,2,3],[4,5,6],[7,8,9]]]).reshape(-1)
print("The Array After reshaping is:-")
print(arr23)

The Before reshaping is:- [[[1 2 3]
  [4 5 6]
  [7 8 9]]]

The Array After reshaping is:-
[1 2 3 4 5 6 7 8 9]


# Acessing Array Elements,Indexing And Slicing Functions 

In [27]:
arr24=np.array([1,2,3,4,5,6]) 
              # 0,1,2,3,4,5
print("The Element Is:-",arr24[3])

The Element Is:- 4


In [28]:
arr25=np.array([1,2,3,4,5,6])
              # 0,1,2,3,4,5
print(arr25[0:])

[1 2 3 4 5 6]


In [29]:
arr25=np.array([1,2,3,4,5,6])
              # 0,1,2,3,4,5
print(arr25[0:3])

[1 2 3]


In [30]:
arr25=np.array([1,2,3,4,5,6])
              # 0,1,2,3,4,5
print(arr25[-5:])

[2 3 4 5 6]


# Iterating And 1D,2D,3D And n Dimension Arrays

In [31]:
arr27=np.array([1,2,3,4,5,6,7]) # 1D Array Example
for i in arr27:
    print(i)

1
2
3
4
5
6
7


In [32]:
arr27=np.array([[1,2],[3,4],[5,6]]) # 2D Array Example
for i in arr27:
    for j in i:
        print(j)

1
2
3
4
5
6


In [33]:
arr27=np.array([[[1,2,3],[4,5,6],[7,8,9]]]) # 3D Array Example
for i in arr27:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9


In [34]:
arr27=np.array([[[1,2,3],[4,5,6],[7,8,9]]]) # 3D Array Example
for i in np.nditer(arr27): # nditer func is used to loop over and multidimension arrays.
    print(i)

1
2
3
4
5
6
7
8
9


In [35]:
arr28=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr28)
print("The Array is of",arr28.ndim,"Dimensions")
print()
print("The Elements is at which specific position:-")
for i,d in enumerate(arr28):
    print(i,d)

[ 1  2  3  4  5  6  7  8  9 10]
The Array is of 1 Dimensions

The Elements is at which specific position:-
0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 10


# Copy And View Functions

In [36]:
arr30=np.array([1,2,3,4,5,6,7,8,9,10])
arrcopy=arr30.copy() # copy function does not change original array.
print("The Original Array is:-")
print(arr30)
print()
arrcopy[0]=10
print("The Copied Array is:-")
print(arrcopy)

The Original Array is:-
[ 1  2  3  4  5  6  7  8  9 10]

The Copied Array is:-
[10  2  3  4  5  6  7  8  9 10]


In [37]:
import numpy as np

arr31 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arrview = arr31.view()  # View shares the same data, changes affect original

print("The Original Array is:-")
print(arr31)
print()

arrview[0] = 10  # Modifies the original array as well!

print("The Viewed Array is:-")
print(arrview)

print()
print("Original Array after modifying the view:")
print(arr31)


The Original Array is:-
[ 1  2  3  4  5  6  7  8  9 10]

The Viewed Array is:-
[10  2  3  4  5  6  7  8  9 10]

Original Array after modifying the view:
[10  2  3  4  5  6  7  8  9 10]


# Min,Max,Argmin and Cumsum Function

In [38]:
arr32=np.array([[[1,2,3],[40,50,60],[70,80,90]]])
print(arr32.min()) # min func gives the minimum value of an multidimensional / OneD array

1


In [39]:
arr33=np.array([[[1,2,3],[40,50,60],[70,80,90]]])
print(arr32.max()) # max func gives the maximum value of an multidimensional / OneD array

90


In [40]:
# arr34=np.array([[[1,2,3],[40,50,60],[70,80,90]]])
# print(arr32.max().argmin()) # argmin func gives the  value of an index of  multidimensional / OneD array

In [41]:
arr34=np.cumsum([1,2,3,4,5,6,7])
print(arr34)

[ 1  3  6 10 15 21 28]


# Trignometric Functions

In [42]:
arr35=np.sin([1,2,3,4,5,6,7,8,9,10]) # sin function gives the sin value of each number/element
print(arr35)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]


In [43]:
arr36=np.cos([1,2,3,4,5,6,7,8,9,10]) # cos function gives the cos value of each number/element
print(arr36)

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]


# Search And Sorted Functions

In [49]:

arr37 = np.array([1, 2, 3, 4, 5, 6])
result = np.where(arr37 % 2 == 0)  # Find indices of even numbers

print("Indices of even numbers:", result)
print("Even numbers:", arr37[result])


Indices of even numbers: (array([1, 3, 5]),)
Even numbers: [2 4 6]


In [50]:
arr38=np.array([2,7,9,10,50,60])
sorted_array=np.sort(arr38)
print(sorted_array)

[ 2  7  9 10 50 60]


In [58]:
arr2d = np.array([[3, 1, 2],
                  [6, 5, 4]])

sorted_rowwise = np.sort(arr2d, axis=1)  # Sort each row
sorted_colwise = np.sort(arr2d, axis=0)  # Sort each column

print("Original:\n", arr2d)
print("Sorted row-wise:\n", sorted_rowwise)
print("Sorted column-wise:\n", sorted_colwise)


Original:
 [[3 1 2]
 [6 5 4]]
Sorted row-wise:
 [[1 2 3]
 [4 5 6]]
Sorted column-wise:
 [[3 1 2]
 [6 5 4]]


In [62]:
arr40 = np.array([[4, 2],[1, 3]])
sorted_flat = np.sort(arr40, axis=None)
print("Sorted flattened array:", sorted_flat)

Sorted flattened array: [1 2 3 4]


# Shuffle,Unique Array Function

In [71]:
arr41=np.array([1,2,3,4,5])
np.random.shuffle(arr41)
print(arr41)

[1 3 2 5 4]


In [75]:
arr42=np.array([1,2,3,4,4,5,5,5,6,6,7,8,9,9,10])
unique=np.unique(arr42)
print(unique)

[ 1  2  3  4  5  6  7  8  9 10]


# Inserting Element in Array Functions

In [77]:
arr43=np.array([2,3,4,5,6])
inserted=np.insert(arr43,0,1)
                # arraynam,idxnum,value_to_be_inserted
print(inserted)

[1 2 3 4 5 6]
